import {
  CAMINHOS_QUE_TRILHAMOS,
  CHAVAO_ABRE_PORTAS,
  NAO_ADIANTA_TER_RESPOSTA,
  O_CHAO_O_TETO,
  QUANDO_O_CORPO,
  RACISMOS_INTIMOS,
} from "./escrituras";
import { IBEJIS } from "./ibejis";
import { PONTA_DE_ANZOL } from "./pontaDeAnzol";

export const ALL_MOVIES = [
  ...QUANDO_O_CORPO,
  ...NAO_ADIANTA_TER_RESPOSTA,
  ...O_CHAO_O_TETO,
  ...CHAVAO_ABRE_PORTAS,
  ...RACISMOS_INTIMOS,
  ...CAMINHOS_QUE_TRILHAMOS,
  ...IBEJIS,
  ...PONTA_DE_ANZOL,
];
