export const SITE_CONTENT = {
  mostras: [
    {
      id: "abertura",
      type: "mostra",
      title: "Sessão de Abertura",
      shortTitle: "ABER-TURA",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/abertura",
      color: "var(--color-green)",
    },
    {
      id: "homenagem",
      type: "mostra",
      title: "Homenagem",
      shortTitle: "HOME-NAGEM",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/homenagem",
      color: "var(--color-earth)",
    },
    {
      id: "cineEscrituras",
      type: "mostra",
      title: "Cine-Escrituras Pretas",
      shortTitle: "CINE-ESCRITURAS PRETAS",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/cineEscrituras",
      color: "var(--color-blue-300)",
    },
    {
      id: "internacional",
      type: "mostra",
      title: "Internacional",
      shortTitle: "INTERNA-CIONAL",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/internacional",
      color: "var(--color-lilac)",
    },
    {
      id: "quilombola",
      type: "mostra",
      title: "Quilombola",
      shortTitle: "QUILOM-BOLA",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/quilombola",
      color: "var(--color-blue-200)",
    },
    {
      id: "infantil",
      type: "mostra",
      title: "Infantil",
      shortTitle: "INFAN-TIL",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/infantil",
      color: "var(--color-olive)",
    },
    {
      id: "especial",
      type: "mostra",
      title: "Especial",
      shortTitle: "ESPE-CIAL",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      longDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu mauris a urna tincidunt mattis quis eu orci. Nulla facilisi. Maecenas dignissim, est sit amet faucibus aliquam, quam augue congue magna, a aliquam nunc quam dapibus augue. Nam tempus commodo odio, pellentesque rhoncus lacus venenatis eu. Maecenas ultricies massa consequat ex tincidunt, at luctus nisl feugiat. Nunc rutrum luctus enim, a dictum magna tincidunt vitae. Nullam placerat lacinia ex, non rutrum est auctor id. Vestibulum vitae tellus molestie, sodales libero efficitur, porttitor ipsum. Nam eleifend ipsum sed purus dignissim tempus non ac neque. Morbi dolor dolor, aliquet id ligula eu, imperdiet semper turpis. Integer ut.`,
      url: "/mostras/especial",
      color: "var(--color-pink)",
    },
  ],
  atividades: [
    {
      id: "atividades",
      type: "atividades",
      title: "Atividades formativas",
      description: `Esta mostra celebra o cinema negro, reunindo filmes que abordam identidade, ancestralidade e resistência. O público é convidado a refletir sobre questões sociais e históricas, com destaque para produções independentes e inovadoras. O evento oferece debates, oficinas e homenagens, ampliando o protagonismo de artistas negros no audiovisual. O objetivo é inspirar novas gerações, fortalecer redes de colaboração e celebrar conquistas, reafirmando o compromisso com a pluralidade e a inclusão.`,
      url: "/atividades-formativas",
      color: "var(--color-pink)",
    },
  ],
  socials: [
    {
      id: "1",
      title: "instagram",
      link: "https://www.instagram.com/semana.cinemanegrobh/",
    },
  ],
};
